name: Sync Upstream

on:
  schedule:
    # 每天 UTC 时间 0 点自动运行（北京时间 8 点）
    - cron: '0 0 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Fork
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # 获取完整提交历史

      - name: Add Upstream Remote
        run: |
          git remote add upstream https://github.com/jaywcjlove/reference.git
          git fetch upstream

      - name: Merge Upstream Changes
        run: |
          git checkout main  # 如果是 "master" 分支则替换
          git merge upstream/main  # 同步上游 main 分支
          git push origin main
